# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('care_of_person', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(max_length=64)),
                ('house_no', models.IntegerField()),
                ('post_code', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile', models.CharField(blank=True, max_length=128, null=True)),
                ('one_liner_address', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commons_contact_creator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commons_contact_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
