# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('remark', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_address', to='commons.Contact')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_warehouse_creator', to=settings.AUTH_USER_MODEL)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_curator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_warehouse_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseassets_asset', to='asset.Asset')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_warehouseassets_creator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_warehouseassets_editor', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseassets_warehouse', to='warehouse.Warehouse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='warehouseassets',
            unique_together=set([('warehouse', 'asset')]),
        ),
    ]
