# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=64)),
                ('size', models.CharField(blank=True, max_length=32, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(null=True, upload_to='/media/Y/m/d')),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assetbrand_creator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assetbrand_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assetgroup_creator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assetgroup_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_brand', to='asset.AssetBrand'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_group', to='asset.AssetGroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_asset_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='modifiedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_asset_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
