# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_asset', to='asset.Asset')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_assigner', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_incoming', to='people.Person')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_incoming_creator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_incoming_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_asset', to='asset.Asset')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_outgoing_creator', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_outgoing_editor', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_assigner', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_incoming', to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
