# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='assigned_by',
            new_name='received_by',
        ),
        migrations.RenameField(
            model_name='incoming',
            old_name='assigned_to',
            new_name='returned_by',
        ),
        migrations.RenameField(
            model_name='outgoing',
            old_name='received_by',
            new_name='assigned_by',
        ),
        migrations.RenameField(
            model_name='outgoing',
            old_name='returned_by',
            new_name='assigned_to',
        ),
    ]
