# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160624_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='returned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_returned_by', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_assigned_to', to='people.Person'),
        ),
    ]
