# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Assignee', 'verbose_name_plural': 'Assignees'},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'verbose_name': 'Assignee Type', 'verbose_name_plural': 'Assignee Types'},
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_type', to='people.PersonType', verbose_name='Assignee Type'),
        ),
    ]
